" Deactivate the arrow keys.
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
vnoremap <Up> <Nop>
vnoremap <Down> <Nop>
vnoremap <Left> <Nop>
vnoremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

" erases the highlight on search
map <silent> <leader><CR> :noh<CR>

" side pane of files (n is for nerdtree)
nnoremap <leader>n :NERDTreeToggle<cr>

" reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

nmap <leader>P <Plug>yankstack_substitute_newer_paste
nmap <leader>p <Plug>yankstack_substitute_older_paste

let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_next_key='<C-m>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_quit_key='<esc>'

let g:AutoClosePreserveDotReg = 0

" Airline configuration.
let g:airline_solarized_bg='dark'
set t_Co=256 " use 256 colors

" Have JJ command erase supplementary spaces.
if v:version > 703 || v:version == 703 && has('patch541')
  set formatoptions+=j
endif

" UltiSnips snippets engine.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-n>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"
let g:UltiSnipsSnippetDirectories=["~/.files/conf/vim/snips/"]

" Automatically indent if CR is entered after an expansion.
let g:delimitMate_expand_cr=1

" In terminal mode, use escape to leave terminal.
:tnoremap <Esc> <C-\><C-n>

exe 'set rtp+=' . expand('~/.files/conf/vim/')
luafile ~/.files/conf/vim/lua/init.lua
