# -----------------------------------------------------------------------------
# initialization
# -----------------------------------------------------------------------------

# Themes are in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

DOTFILES_DIR="/home/ben/.files"

MOZ_SM_SRC_DIR="/home/ben/code/mozilla-inbound/js/src"

# Normal plugins are in $ZSH/plugins/, custom plugins are in $ZSH/custom/plugins/
plugins=(git sudo command-not-found)

# Programs to activate
ZSH=$HOME/.files/bin/ohmyzsh
source $ZSH/oh-my-zsh.sh

source ~/.files/bin/z/z.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# -----------------------------------------------------------------------------
# global variables
# -----------------------------------------------------------------------------

export PROMPT='%{$fg[red]%}%n%{$fg[magenta]%}@%{$fg[yellow]%}%m %{$fg[cyan]%}[%c%\]
${ret_status}%{$reset_color%}'

export PATH="$DOTFILES_DIR/bin:$DOTFILES_DIR/private/bin:/home/ben/.cargo/bin:/home/ben/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$PATH"

if [ -e ~/bin ]
then
    export PATH=${PATH}:$(find ~/bin -type d | tr '\n' ':' | sed 's/:$//')
fi

export MANPATH="/usr/local/man:$MANPATH"
export LC_ALL="en_US.UTF-8"

# Rust source code path.
if [ -d "/home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src" ]
then
    RUST_SRC_PATH="/home/ben/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
    export RUST_SRC_PATH
fi

# mozilla build shortcuts
export BUILD_VERBOSE_LOG=1

# -----------------------------------------------------------------------------
# aliases
# -----------------------------------------------------------------------------

NUM_CPUS=`nproc`

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias b='./build.sh && m'

alias c="cb"
alias cb="cargo build"

alias d='docker'
alias dc='docker-compose'

alias fbn='find ./ -name $1'

alias h='hg'

alias jit='$MOZ_SM_SRC_DIR/jit-test/jit_test.py'
alias jitz='$MOZ_SM_SRC_DIR/jit-test/jit_test.py ./dist/bin/js'

alias m="make -sj$NUM_CPUS"
alias meteo='curl -4 wttr.in/Lyon'
alias mrproper='mv build.sh /tmp/build.sh && (rm -rf ./* .deps) && mv /tmp/build.sh ./ && b'
alias ms='make -s 2>&1 | less'

alias op='gnome-open'

alias paint='pinta'
alias psg='ps aux | grep $1'
alias py='python3'

alias serve='python -m SimpleHTTPServer'

alias tmux='TERM=screen-256color-bce tmux' # 256 colors mode by default.
alias try='cd $MOZ_SM_SRC_DIR && cd ../.. && ./mach try -b do -p all -u jsreftest,jittests -t none'

alias upvim='nvim +PlugInstall +UpdateRemotePlugins +qa'

# -----------------------------------------------------------------------------
# common typos
# -----------------------------------------------------------------------------

alias gh='hg'
alias sl='ls'

# -----------------------------------------------------------------------------
# better cli tools
# -----------------------------------------------------------------------------

[ -f /usr/bin/ncdu ] && alias du="ncdu -rr -x --exclude .git --exclude node_modules"
which bat >/dev/null 2>&1 && alias cat=bat
which tldr >/dev/null 2>&1 && alias help=tldr
